### ISSUE TITLE
Transfer from ETH GitLab

### ISSUE THREAD

**Issue by gteufelberger** [gteufelberger/vo-scraper#1]
Things to do while migrating from https://gitlab.ethz.ch/tgeorg/vo-scraper to GitHub

- [x] Copy over all current releases
- [x] Push update linking to GitHub
- [x] Update README on GitLab
- [x] Switch from GitLab CI to GitHub Actions -> #4
- [x] Post transfer tasks:
    - [x] Format project -> 38630350ee9606a9c42ca561805d1e793eae1bac
    - [x] Add linting CI -> #7
    - [x] Add formatting CI -> #6
